#
#  Copyright (c) 2023 SAP SE
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
#
#  Contributors:
#       SAP SE - initial implementation
#

{{- if .Values.containerEnvironmentVariables }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "pod-{{ required "A valid application name is required! (.Values.appName)" .Values.appName }}"
  namespace: {{ required "A valid namespace is required! (.Values.namespace)" .Values.namespace }}
data:
  {{- range $key, $value := .Values.containerEnvironmentVariables }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}