---
{{- $imageCredentials := .Values.imageCredentials.enabled -}}
{{- if $imageCredentials }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: "docker-registry-github-{{ required "A valid application name is required! (.Values.appName)" .Values.appName }}"
  namespace: {{ required "A valid namespace is required! (.Values.namespace)" .Values.namespace }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}