---
# The chart API version (required)
apiVersion: v2
# The name of the chart (required)
name: generic-module
# A single-sentence description of this project (optional)
description: A Helm chart for generic SPAICER modules and applications

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.1"

# A list of URLs to source code for this project (optional)
sources: ["https://github.wdf.sap.corp/IoTInnovation/sap-ids-dsc-infrastructure/tree/development/helm/charts"]

engine: gotpl
# A SemVer range of compatible Kubernetes versions (optional)
kubeVersion: ">=1.21.3"
# Whether this chart is deprecated (optional, boolean)
deprecated: false
# The URL of this projects home page (optional)
home: ""
# A URL to an SVG or PNG image to be used as an icon (optional).
#icon: "https://..."

maintainers:
  - name: SAP Alexandru Danciu
    email: alexandru.danciu@sap.com
    url: "https://github.com/alexandrudanciu"

annotations:
  sub-helm-chart: true