apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "dataspace-connector.fullname" . }}-certs
  labels:
    {{- include "dataspace-connector.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "dataspace-connector.gen-certs" . ) | indent 2 }}
  {{- $files := .Files }}
  {{- range tuple "truststore.p12" "keystore.p12"}}
  {{ . }}: |-
        {{ $files.Get . | b64enc}}
  {{- end }}
