apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "dataspace-connector.fullname" . }}-config
  labels:
    {{- include "dataspace-connector.labels" . | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range tuple "config.json" "log4j2.xml"}}
  {{ . }}: |-
        {{ $files.Get . | b64enc}}
  {{- end }}
