apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.global.oauth2_proxy_name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ required "A valid url is required! (.Values.global.authDomain)" .Values.global.authDomain  }}.{{ required "A valid url is required! (.Values.global.domain)" .Values.global.domain  }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.global.oauth2_proxy_name }}
                port:
                  number: 4180
  tls:
    - hosts:
        - {{ required "A valid url is required! (.Values.global.authDomain)" .Values.global.authDomain  }}.{{ required "A valid url is required! (.Values.global.domain)" .Values.global.domain  }}
      secretName: www-tls