apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emqx-api
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.emqxmqttbroker.subDomainApi }}.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.emqxmqttbroker.fullnameOverride }}
                port:
                  number: 8081