#
#  Copyright (c) 2023 SAP SE
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
#
#  Contributors:
#       SAP SE - initial implementation
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-configmap
  labels:
    app: kong-configmap
data:
  kong.yml: |-
{{ tpl (.Files.Get "kong.dbless.yaml" | indent 4) . }}