apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "oauth2-proxy-secret"
  namespace: {{ .Release.Namespace }}
data:
  client-id: {{ .Values.global.oauth_client_id }}
  client-secret: {{ .Values.global.oauth_client_secret }}
  cookie-secret: {{ randAlphaNum 16 | b64enc }}