#
#  Copyright (c) 2023 SAP SE
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
#
#  Contributors:
#       SAP SE - initial implementation
#

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "oauth2-proxy-secret"
  namespace: {{ .Release.Namespace }}
data:
  client-id: {{ .Values.global.oauth_client_id }}
  client-secret: {{ .Values.global.oauth_client_secret }}
  cookie-secret: {{ randAlphaNum 16 | b64enc }}