#
#  Copyright (c) 2023 SAP SE
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
#
#  Contributors:
#       SAP SE - initial implementation
#

---
apiVersion: v2
name: spaicer-platform
description: An Umbrella Helm chart for the SPAICER Platform (Edge)

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
# type: library
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "v0.0.1"

# TODO change:
home: "https://github.com/spaicer/service-offering-cicd-template"

maintainers:
  - name: SAP Alexandru Danciu
    email: alexandru.danciu@sap.com
    url: "https://github.com/alexandrudanciu"

icon: "https://www.spaicer.de/wp-content/uploads/2019/05/logo_spaicer_250.png"

annotations:
  dataspaceconnector-version: "v6.5.1"
  umbrella-helm-chart: true

dependencies:
  - name: ingress-nginx
    version: "4.0.6"
    repository: "https://kubernetes.github.io/ingress-nginx"
    alias: ingress
    tags:
      - nginx

  - name: cert-manager
    version: "1.7.2" # @see https://github.com/SAP/sap-btp-service-operator/issues/101
    repository: "https://charts.jetstack.io"
    tags:
      - cert-manager

#  - name: dataspace-connector
#    version: "0.2.8"
#    repository: "file://../../charts/dataspaceconnector-v6.5.1"
#    alias: dataspaceconnector
#    tags:
#      - dsc

  - name: postgresql
    alias: postgres
    version: 12.1.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgres.enabled

  - name: vault
    version: 0.20.0
    repository: https://helm.releases.hashicorp.com
    alias: vault
    condition: vault.enabled

  - name: tractusx-connector
    version: "0.3.2"
    repository: "https://catenax-ng.github.io/tx-tractusx-edc"
    alias: tractusxconnector
    condition: tractusxconnector.enabled

  - name: emqx
    version: "4.3.10"
    repository: "https://repos.emqx.io/charts"
    alias: emqxmqttbroker
    condition: emqxmqttbroker.enabled
    tags:
      - emqx

  - name: node-red
    version: "9.0.0"
    repository: "https://k8s-at-home.com/charts/"
    alias: nodered
    condition: nodered.enabled
    tags:
      - nodered

  - name: kong
    version: "2.6.3"
    repository: "https://charts.konghq.com"
    alias: kong
    condition: kong.enabled
    tags:
      - kong

# Wait for airflow helm chart version 1.4.0 to fix db migration timeout
  - name: airflow
    version: "1.4.0"#"8.5.2"
    repository: "https://airflow.apache.org"#"https://airflow-helm.github.io/charts"
    alias: airflow
    condition: airflow.enabled
    tags:
      - airflow

  - name: generic-module
    version: "0.0.1"
    repository: "file://../../charts/generic-module"
    alias: digitalcoilbackend
    condition: digitalcoilbackend.enabled
    tags:
      - prototype-uc1-narrative1-digital-coil

  - name: generic-module
    version: "0.0.1"
    repository: "file://../../charts/generic-module"
    alias: digitalcoilui
    condition: digitalcoilui.enabled
    tags:
      - digital-coil-ui

  - name: generic-module
    version: "0.0.1"
    repository: "file://../../charts/generic-module"
    alias: annotatormodule
    condition: annotatormodule.enabled
    tags:
      - annotator-module

  # Supply Chain Analyzer UI and Backend
  - name: generic-module
    version: "0.0.1"
    repository: "file://../../charts/generic-module"
    alias: supplychainanalyzer
    condition: supplychainanalyzer.enabled
    tags:
      - supply-chain-analyzer

  - name: generic-module
    version: "0.0.1"
    repository: "file://../../charts/generic-module"
    alias: supplychainui
    condition: supplychainui.enabled
    tags:
      - supply-chain-ui

  # Maintenance Level Prediction UI and Backend
  - name: generic-module
    version: "0.0.1"
    repository: "file://../../charts/generic-module"
    alias: maintenancelevelpredictionui
    condition: maintenancelevelpredictionui.enabled
    tags:
      - maintenance-level-prediction-ui

  - name: generic-module
    version: "0.0.1"
    repository: "file://../../charts/generic-module"
    alias: ap7maintenancelevelprediction
    condition: ap7maintenancelevelprediction.enabled
    tags:
      - ap7-maintenance-level-prediction