#
#  Copyright (c) 2023 SAP SE
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
#
#  Contributors:
#       SAP SE - initial implementation
#

_format_version: "1.1"
services:
  - connect_timeout: 60000
    host: annotator-module.spaicerns1.svc.cluster.local
    name: annotator-module
    port: 8080
    protocol: http
    read_timeout: 60000
    retries: 5
    write_timeout: 60000
    routes:
      - name: annotator-module
        paths:
          - /annotator-module
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        strip_path: true
        https_redirect_status_code: 426
consumers:
  - username: developer
keyauth_credentials:
  - consumer: developer
plugins:
  - name: prometheus
    enabled: true
    protocols:
      - grpc
      - grpcs
      - http
      - https
  - name: key-auth
    config:
      key_names:
        - apikey
      key_in_body: false
      key_in_header: true
      key_in_query: true
      hide_credentials: false
      run_on_preflight: true
