apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  namespace: {{ .Release.Namespace }}
  name: testsecret-tls
  labels:
    {{- include "dataspace-connector.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "dataspace-connector.gen-certs" . ) | indent 2 }}
