name: CI

on: [push]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  #Job for publishing the application bundle (bundled service offering) to an OCI-compliant repository (i.e., GitHub Packages).
  porter:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@main

      - name: Setup Porter
        uses: getporter/gh-action@v0.1.3

      - name: Install Porter Helm3 mixin
        run: porter mixins install helm3

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Porter Publish
        run: porter publish